# .Site configuration
baseurl = "/"
defaultContentLanguage = "pt-br"
languageCode = "pt-br"
theme = "mateusfccp.me"
publishDir = "/usr/share/nginx/html"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

disqusShortname = "mateusfccp"

[author]
name = "Mateus Felipe C. C. Pinto"

[params]
dateform        = "2 de Jan de 2006"
dateformShort   = "2 de Jan"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"

# Metadata mostly used in document's head
description  = "Homepage e blog do Mateus Felipe"
homeSubtitle = "Desenvolvedor · Teólogo"
keywords     = "homepage, blog, development, programming, theology"

# Directory name of your blog content
contentTypeName = "posts"
defaultTheme    = "dark"

# Others
enableEmoji = true

# Social
[[params.social]]
name = "twitter"
url  = "https://twitter.com/mateusfccp"

[[params.social]]
name = "email"
url  = "mailto:mateusfccp@gmail.com"

[[params.social]]
name = "github"
url  = "https://github.com/mateusfccp"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/mateusfccp"

[languages]
[languages.pt-br]
title          = "Mateus Felipe"
subtitle       = "Desenvolvedor · Teólogo"
keywords       = "homepage, blog, desenvolvimento, programação"
readOtherPosts = "Ler outros posts"
copyright      = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[languages.pt-br.logo]
logoText     = "[mateusfccp@arch ~]" 
logoHomeLink = "/"

[languages.pt-br.menu]
[[languages.pt-br.menu.main]]
identifier = "about"
name       = "Sobre"
url        = "/about"

[[languages.pt-br.menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/posts"

[languages.en]
title          = "Mateus Felipe"
subtitle       = "Developer · Theologian"
keywords       = "homepage, blog, development, programming"
readOtherPosts = "Read other posts"
copyright      = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[languages.en.logo]
logoText     = "#[get(\"home\")]"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name       = "About"
url        = "/about"

[[languages.en.menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/posts"